name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Change to Script Directory
        run: cd github-actions/remotescrapper
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install certifi==2023.7.22
          pip install charset-normalizer==3.3.2
          pip install idna==3.4
          pip install requests==2.31.0
          pip install urllib3==2.0.7
          pip install xlwt==1.3.0
          
      - name: Install Flake8
        run: |
          
          pip install flake8
     
      - name: Linting
        run: |
          flake8 scrape.py

      - name: Unit Testing
        run: |
          pytest tests/
